overblog_graphql:
  definitions:
    schema:
      default:
        query: Query
      netgen:
        query: NetgenQuery
    mappings:
      types:
        -
          type: yaml
          dir: "%kernel.project_dir%/src/config/graphql/types/"
          suffix: null
