services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Rs\NetgenHeadless\:
    resource: '../../'
    exclude:
        - '../../DependencyInjection/'
        - '../../Entity/'
        - '../../Kernel.php'
        - '../../Tests/'
        - '../../vendor/'

  Rs\NetgenHeadless\GraphQl\ResolverMap:
    tags:
      - { name: overblog_graphql.resolver_map, schema: default }

  Rs\NetgenHeadless\GraphQl\:
    resource: '../../GraphQl/'
