services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Rs\NetgenHeadless\:
    resource: '../../'
    exclude:
        - '../../bin/'
        - '../../DependencyInjection/'
        - '../../Entity/'
        - '../../Kernel.php'
        - '../../Tests/'
        - '../../vendor/'
        - '../../var/'
